name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3.'
runs:
  using: 'node16' # this will tell GitHub Actions that this is a Custom JavaScript Action
  # pre: 'setup.js'
  main: 'main.js'
  # post: 'cleanup.js'
